# Logging configuration
logging.config=classpath:log4j2.xml
spring.output.ansi.enabled=always

# spring mvc??
spring.mvc.async.request-timeout=60000
management.endpoints.web.exposure.include=health,info,metrics,threaddump,loggers